### ISSUE TITLE
fatal error when make

### ISSUE THREAD

**Issue by sybil12** [arnaud-ramey/voronoi#7]
fatal error: gtest/gtest.h: No such file or directory
 #include <gtest/gtest.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
src/CMakeFiles/voronoi.dir/build.make:65: recipe for target 'src/CMakeFiles/voronoi.dir/test_voronoi.cpp.o' failed
make[2]: *** [src/CMakeFiles/voronoi.dir/test_voronoi.cpp.o] Error 1
make[2]: Leaving directory '/home/lidong/code/voronoi/build'
CMakeFiles/Makefile2:88: recipe for target 'src/CMakeFiles/voronoi.dir/all' failed
make[1]: *** [src/CMakeFiles/voronoi.dir/all] Error 2
make[1]: Leaving directory '/home/lidong/code/voronoi/build'
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by krummrey** [comment]
installing gtest might help. https://gist.github.com/Cartexius/4c437c084d6e388288201aadf9c8cdd5
